app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include(('bases.urls','bases'), namespace='bases')),
    path('inv/', include(('inv.urls','inv'), namespace='inv')),
    path('cmp/', include(('cmp.urls','cmp'), namespace='cmp')),
    path('fac/', include(('fac.urls','fac'), namespace='fac')),
    path('admin/', admin.site.urls),
]

inv/urls.py
from django.urls import path
from .views import CategoriaView, CategoriaNew, CategoriaEdit, CategoriaDel, SubCategoriaView, SubCategoriaNew, SubCategoriaEdit, SubCategoriaDel, MarcaView, MarcaNew, MarcaEdit, MarcaInactivate, UnidadMedidaView, UnidadMedidaNew, UnidadMedidaEdit, UnidadMedidaInactivate, ProductoView, ProductoNew, ProductoEdit, ProductoInactivate

urlpatterns = [
    path('categorias/',CategoriaView.as_view(), name='categoria_list'),
    path('categorias/new',CategoriaNew.as_view(), name='categoria_new'),
    path('categorias/edit/<int:pk>',CategoriaEdit.as_view(), name='categoria_edit'),
    path('categorias/delete/<int:pk>',CategoriaDel.as_view(), name='categoria_del'),

    path('subcategorias/',SubCategoriaView.as_view(), name='subcategoria_list'),
    path('subcategorias/new',SubCategoriaNew.as_view(), name='subcategoria_new'),
    path('subcategorias/edit/<int:pk>',SubCategoriaEdit.as_view(), name='subcategoria_edit'),
    path('subcategorias/delete/<int:pk>',SubCategoriaDel.as_view(), name='subcategoria_del'),

    path('marcas/',MarcaView.as_view(), name='marca_list'),
    path('marcas/new',MarcaNew.as_view(), name='marca_new'),
    path('marcas/edit/<int:pk>',MarcaEdit.as_view(), name='marca_edit'),
    path('marcas/inactivate/<int:id>',MarcaInactivate, name='marca_inactivate'),

    path('unidades-medida/',UnidadMedidaView.as_view(), name='unidadmedida_list'),
    path('unidades-medida/new',UnidadMedidaNew.as_view(), name='unidadmedida_new'),
    path('unidades-medida/edit/<int:pk>',UnidadMedidaEdit.as_view(), name='unidadmedida_edit'),
    path('unidades-medida/inactivate/<int:id>',UnidadMedidaInactivate, name='unidadmedida_inactivate'),

    path('productos/',ProductoView.as_view(), name='producto_list'),
    path('productos/new',ProductoNew.as_view(), name='producto_new'),
    path('productos/edit/<int:pk>',ProductoEdit.as_view(), name='producto_edit'),
    path('productos/inactivate/<int:id>',ProductoInactivate, name='producto_inactivate'),
]

bases/models.py
from django.db import models
from django.contrib.auth.models import User

class ClaseModelo(models.Model):
    estado = models.BooleanField(default=True)
    fecha_crea = models.DateTimeField(auto_now_add=True)
    fecha_modif = models.DateTimeField(auto_now=True)
    user_crea =  models.ForeignKey(User, on_delete=models.CASCADE)
    user_modifi = models.IntegerField(blank=True, null=True)

    class Meta:
        abstract = True

inv/models.py
from django.db import models
from django.db.models.deletion import CASCADE
from django.forms.fields import CharField
from bases.models import ClaseModelo

class Categoria(ClaseModelo):
    descripcion = models.CharField(
        max_length = 100,
        help_text = 'Descripcion de la categoria',
        unique = True
    )

    def __str__(self):
        return '{}'.format(self.descripcion)

    def save(self):
        self.descripcion = self.descripcion.upper()
        super(Categoria, self).save()

    class Meta:
        verbose_name_plural = 'Categorias'


class SubCategoria(ClaseModelo):
    categoria = models.ForeignKey(Categoria, on_delete=models.CASCADE)
    descripcion = models.CharField(
        max_length = 100,
        help_text = 'Descripcion de la categoria',
    )

    def __str__(self):
        return '{}:{}'.format(self.categoria.descripcion,self.descripcion)

    def save(self):
        self.descripcion = self.descripcion.upper()
        super(SubCategoria, self).save()
    
    class Meta:
        verbose_name_plural = 'Sub Categorias'
        unique_together = ('categoria','descripcion')


class Marca(ClaseModelo):
    descripcion = models.CharField(
        max_length=100,
        help_text='Descripcion de la marca',
        unique=True
    )

    def __str__(self):
        return '{}'.format(self.descripcion)

    def save(self):
        self.descripcion = self.descripcion.upper()
        super(Marca, self).save()

    class Meta:
        verbose_name_plural = 'Marcas'


class UnidadMedida(ClaseModelo):
    descripcion = models.CharField(
        max_length=100,
        help_text='Descripcion de la unidad',
        unique=True
    )

    def __str__(self):
        return '{}'.format(self.descripcion)

    def save(self):
        self.descripcion = self.descripcion.upper()
        super(UnidadMedida, self).save()

    class Meta:
        verbose_name_plural = 'Unidades de medida'


class Producto(ClaseModelo):
    codigo = models.CharField(
        max_length=20,
        unique=True
    )
    codigo_barras = models.CharField(max_length=50)
    descripcion = models.CharField(max_length=200)
    precio = models.FloatField(default=0)
    existencia = models.IntegerField(default=0)
    ultima_compra = models.DateField(null=True, blank=True)

    marca = models.ForeignKey(Marca, on_delete=models.CASCADE)
    unidad_medida = models.ForeignKey(UnidadMedida, on_delete=models.CASCADE)
    subcategoria = models.ForeignKey(SubCategoria, on_delete=models.CASCADE)

    def __str__(self):
        return '{}'.format(self.descripcion)

    def save(self):
        self.descripcion = self.descripcion.upper()
        super(Producto, self).save()

    class Meta:
        verbose_name_plural = 'Productos'
        unique_together = ('codigo', 'codigo_barras')

inv/views.py
from django.contrib.messages.api import success
from django.shortcuts import render, redirect, resolve_url
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.views import generic
from .models import Categoria, SubCategoria, Marca, UnidadMedida, Producto
from .forms import CategoriaForm, SubCategoriaForm, MarcaForm, UnidadMedidaForm, ProductoForm
from django.urls import reverse_lazy
#mensajes para funciones
from django.contrib import messages
#mensajes para clases
from django.contrib.messages.views import SuccessMessageMixin
#para pasarle la funcion sin privilegios a clases
from bases.views import SinPrivilegios
#para pasarle la funcion login y permission a las funciones
from django.contrib.auth.decorators import login_required, permission_required


class CategoriaView(SinPrivilegios, generic.ListView):
    permission_required = 'inv.view_categoria'
    model = Categoria
    template_name = 'inv/categoria_list.html'
    context_object_name = 'obj'


class CategoriaNew(SuccessMessageMixin, SinPrivilegios, generic.CreateView):
    permission_required = 'inv.add_categoria'
    model = Categoria
    template_name = 'inv/categoria_form.html'
    context_object_name = 'obj'
    form_class = CategoriaForm
    success_message = 'Categoria creada'
    success_url = reverse_lazy('inv:categoria_list')

    def form_valid(self, form):
        form.instance.user_crea = self.request.user
        return super().form_valid(form)


class CategoriaEdit(SuccessMessageMixin, SinPrivilegios, generic.UpdateView):
    permission_required = 'inv.change_categoria'
    model = Categoria
    template_name = 'inv/categoria_form.html'
    context_object_name = 'obj'
    form_class = CategoriaForm
    success_message = 'Categoria actualizada'
    success_url = reverse_lazy('inv:categoria_list')

    def form_valid(self, form):
        form.instance.user_modifi = self.request.user.id
        return super().form_valid(form)


class CategoriaDel(SuccessMessageMixin, SinPrivilegios, generic.DeleteView):
    permission_required = 'inv.delete_categoria'
    model = Categoria
    template_name = 'inv/categoria_del.html'
    context_object_name = 'obj'
    success_message = 'Categoria eliminada'
    success_url = reverse_lazy('inv:categoria_list')


class SubCategoriaView(SinPrivilegios, generic.ListView):
    permission_required = 'inv.view_subcategoria'
    model = SubCategoria
    template_name = 'inv/subcategoria_list.html'
    context_object_name = 'obj'


class SubCategoriaNew(SuccessMessageMixin, SinPrivilegios, generic.CreateView):
    permission_required = 'inv.add_subcategoria'
    model = SubCategoria
    template_name = 'inv/subcategoria_form.html'
    context_object_name = 'obj'
    form_class = SubCategoriaForm
    success_message = 'Subcategoria creada'
    success_url = reverse_lazy('inv:subcategoria_list')

    def form_valid(self, form):
        form.instance.user_crea = self.request.user
        return super().form_valid(form)


class SubCategoriaEdit(SuccessMessageMixin, SinPrivilegios, generic.UpdateView):
    permission_required = 'inv.change_subcategoria'
    model = SubCategoria
    template_name = 'inv/subcategoria_form.html'
    context_object_name = 'obj'
    form_class = SubCategoriaForm
    success_message = 'Subcategoria actualizada'
    success_url = reverse_lazy('inv:subcategoria_list')

    def form_valid(self, form):
        form.instance.user_modifi = self.request.user.id
        return super().form_valid(form)


class SubCategoriaDel(SuccessMessageMixin, SinPrivilegios, generic.DeleteView):
    permission_required = 'inv.delete_subcategoria'
    model = SubCategoria
    template_name = 'inv/categoria_del.html'
    context_object_name = 'obj'
    success_message = 'Subcategoria eliminada'
    success_url = reverse_lazy('inv:subcategoria_list')


class MarcaView(SinPrivilegios, generic.ListView):
    permission_required = 'inv.view_marca'
    model = Marca
    template_name = 'inv/marca_list.html'
    context_object_name = 'obj'


class MarcaNew(SuccessMessageMixin, SinPrivilegios, generic.CreateView):
    permission_required = 'inv.add_marca'
    model = Marca
    template_name = 'inv/marca_form.html'
    context_object_name = 'obj'
    form_class = MarcaForm
    success_message = 'marca creada'
    success_url = reverse_lazy('inv:marca_list')

    def form_valid(self, form):
        form.instance.user_crea = self.request.user
        return super().form_valid(form)


class MarcaEdit(SuccessMessageMixin, SinPrivilegios, generic.UpdateView):
    permission_required = 'inv.change_marca'
    model = Marca
    template_name = 'inv/marca_form.html'
    context_object_name = 'obj'
    form_class = MarcaForm
    success_message = 'marca actializada'
    success_url = reverse_lazy('inv:marca_list')

    def form_valid(self, form):
        form.instance.user_modifi = self.request.user.id
        return super().form_valid(form)


@login_required(login_url='/login/')
@permission_required('inv.change_marca',login_url='bases:sin_privilegios')
def MarcaInactivate(request, id):
    marca = Marca.objects.filter(pk=id).first()
    contexto = {}
    template_name = 'inv/categoria_del.html'

    if not marca:
        return redirect('inv:marca_list')

    if request.method == 'GET':
        contexto = {'obj':marca}

    if request.method == 'POST':
        marca.estado = False
        marca.save()
        messages.success(request, 'Marca inactivada')
        return redirect('inv:marca_list')

    return render(request, template_name, contexto)


class UnidadMedidaView(SinPrivilegios, generic.ListView):
    permission_required = 'inv.view_unidadmedida'
    model = UnidadMedida
    template_name = 'inv/unidadmedida_list.html'
    context_object_name = 'obj'
    

class UnidadMedidaNew(SuccessMessageMixin, SinPrivilegios, generic.CreateView):
    permission_required = 'inv.add_unidadmedida'
    model = UnidadMedida
    template_name = 'inv/unidadmedida_form.html'
    context_object_name = 'obj'
    form_class = UnidadMedidaForm
    success_message = 'unidad de medida creada'
    success_url = reverse_lazy('inv:unidadmedida_list')

    def form_valid(self, form):
        form.instance.user_crea = self.request.user
        return super().form_valid(form)


class UnidadMedidaEdit(SuccessMessageMixin, SinPrivilegios, generic.UpdateView):
    permission_required = 'inv.change_unidadmedida'
    model = UnidadMedida
    template_name = 'inv/unidadmedida_form.html'
    context_object_name = 'obj'
    form_class = UnidadMedidaForm
    success_message = 'unidad de medida actualizada'
    success_url = reverse_lazy('inv:unidadmedida_list')

    def form_valid(self, form):
        form.instance.user_modifi = self.request.user.id
        return super().form_valid(form)


@login_required(login_url='/login/')
@permission_required('inv.change_unidadmedida',login_url='bases:sin_privilegios')
def UnidadMedidaInactivate(request, id):
    unidadMedida = UnidadMedida.objects.filter(pk=id).first()
    contexto = {}
    template_name = 'inv/categoria_del.html'

    if not unidadMedida:
        return redirect('inv:unidadmedida_list')

    if request.method == 'GET':
        contexto = {'obj':unidadMedida}

    if request.method == 'POST':
        unidadMedida.estado = False
        unidadMedida.save()
        messages.success(request, 'Unidad de medida inactivada')
        return redirect('inv:unidadmedida_list')

    return render(request, template_name, contexto)


class ProductoView(SinPrivilegios, generic.ListView):
    permission_required = 'inv.view_producto'
    model = Producto
    template_name = 'inv/producto_list.html'
    context_object_name = 'obj'


class ProductoNew(SuccessMessageMixin, SinPrivilegios, generic.CreateView):
    permission_required = 'inv.add_producto'
    model = Producto
    template_name = 'inv/producto_form.html'
    context_object_name = 'obj'
    form_class = ProductoForm
    success_message = 'producto creado'
    success_url = reverse_lazy('inv:producto_list')

    def form_valid(self, form):
        form.instance.user_crea = self.request.user
        return super().form_valid(form)


class ProductoEdit(SuccessMessageMixin, SinPrivilegios, generic.UpdateView):
    permission_required = 'inv.change_producto'
    model = Producto
    template_name = 'inv/producto_form.html'
    context_object_name = 'obj'
    form_class = ProductoForm
    success_message = 'producto actualizado'
    success_url = reverse_lazy('inv:producto_list')

    def form_valid(self, form):
        form.instance.user_modifi = self.request.user.id
        return super().form_valid(form)


@login_required(login_url='/login/')
@permission_required('inv.change_producto',login_url='bases:sin_privilegios')
def ProductoInactivate(request, id):
    producto = Producto.objects.filter(pk=id).first()
    contexto = {}
    template_name = 'inv/categoria_del.html'

    if not producto:
        return redirect('inv:producto_list')

    if request.method == 'GET':
        contexto = {'obj':producto}

    if request.method == 'POST':
        producto.estado = False
        producto.save()
        messages.success(request, 'Producto inactivada')
        return redirect('inv:producto_list')

    return render(request, template_name, contexto)

inv/templates/inv/categoria_del.html
{% extends 'base/layout.html' %}
{% block title %}Eliminar Categoria{% endblock %}

{% block page_content %}
<form method="POST" class="form-inline">
    {% csrf_token %}
    <div class="col-xl-3 col-md-6 mb-4">
        <div class="card border-left-danger shadow h-100 py-2">
            <div class="card-body">
                <div class="row no-gutters align-items-center">
                    <div class="col mr-2">
                        <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">
                            ¿Eliminar {{ obj.descripcion }}?</div>
                        <button type="submit" class="btn btn-danger"><i
                                class="far fa-question-circle"></i>Eliminar</button>
                        <a href="{{ request.META.HTTP_REFERER }}" class="btn btn-success"><span
                                class="fa fa-undo"></span>Cancelar</a>
                    </div>
                    <div class="col-auto">
                        <i class="far fa-question-circle fa-2x text-gray-300"></i>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>
{% endblock page_content %}
{% block js_page %}
{% endblock js_page %}

inv/templates/inv/categoria_list.html
{% extends 'base/layout.html' %}
{% block title %}Categorias de inventario{% endblock %}

{% block page_content %}
<!-- Dropdown Card Example -->
<div class="card shadow mb-4">
    <!-- Card Header - Dropdown -->
    <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
        <h6 class="m-0 font-weight-bold text-primary">Listado de categorias</h6>
        <div class="dropdown no-arrow">
            <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown"
                aria-haspopup="true" aria-expanded="false">
                <i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"></i>
            </a>
            <div class="dropdown-menu dropdown-menu-right shadow animated--fade-in" aria-labelledby="dropdownMenuLink">
                <div class="dropdown-header">Acciones:</div>
                <a class="dropdown-item" href="{% url 'inv:categoria_new' %}"><i class="far fa-calendar-plus"></i> Nueva</a>
            </div>
        </div>
    </div>
    <!-- Card Body -->
    <div class="card-body">
        {% if not obj %}
            <div class="alert alert-info">No hay categorias</div>
        {% else %}
        <table class="table table-striped table-hover">
            <thead>
                <th>Id</th>
                <th>Descripcion</th>
                <th>Estado</th>
                <th>Fecha Creado</th>
                <th>Fecha Modificado</th>
                <th class="all">Acciones</th>
            </thead>
            <tbody>
                {% for item in obj %}
                    <tr>
                        <td>{{ item.id }}</td>
                        <td>{{ item.descripcion }}</td>
                        <td>{{ item.estado|yesno:"Activo,Inactivo" }}</td>
                        <td>{{ item.fecha_crea|date:"d/m/Y H:i:s" }}</td>
                        <td>{{ item.fecha_modif|date:"d/m/Y H:i:s" }}</td>
                        <td>
                            <a href="{% url 'inv:categoria_edit' item.id %}" class="btn btn-warning btn-circle" role="button"><i class="far fa-edit"></i></a>
                            <a href="{% url 'inv:categoria_del' item.id %}" class="btn btn-danger btn-circle" role="button"><i class="far fa-trash-alt"></i></a>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
        {% endif %}
    </div>
</div>

{% endblock page_content %}

{% block js_page %}
<script>
    //call the datatables jquery plugin
    $(document).ready(function () {
        $('.table').DataTable({
            "language": {
                "sProcessing": "Procesando...",
                "sLengthMenu": "Mostrar _MENU_ registros",
                "sZeroRecords": "No se encontraron resultados",
                "sEmptyTable": "Ningún dato disponible en esta tabla",
                "sInfo": "Mostrando registros del _START_ al _END_ de un total de _TOTAL_ registros",
                "sInfoEmpty": "Mostrando registros del 0 al 0 de un total de 0 registros",
                "sInfoFiltered": "(filtrado de un total de _MAX_ registros)",
                "sInfoPostFix": "",
                "sSearch": "Buscar:",
                "sUrl": "",
                "sInfoThousands": ",",
                "sLoadingRecords": "Cargando...",
                "oPaginate": {
                    "sFirst": "<span class='fa fa-angle-double-left'></span>",
                    "sLast": "<span class='fa fa-angle-double-right'></span>",
                    "sNext": "<span class='fa fa-angle-right'></span>",
                    "sPrevious": "<span class='fa fa-angle-left'></span>"
                },
                "oAria": {
                    "sSortAscending": ": Activar para ordenar la columna de manera ascendente",
                    "sSortDescending": ": Activar para ordenar la columna de manera descendente"
                }
            }
        });
    });
</script>
{% endblock js_page %}

inv/templates/inv/marca_list.html
{% extends 'base/layout.html' %}
{% block title %}Categorias de inventario{% endblock %}

{% block page_content %}
<!-- Dropdown Card Example -->
<div class="card shadow mb-4">
    <!-- Card Header - Dropdown -->
    <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
        <h6 class="m-0 font-weight-bold text-primary">Listado de marcas</h6>
        <div class="dropdown no-arrow">
            <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown"
                aria-haspopup="true" aria-expanded="false">
                <i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"></i>
            </a>
            <div class="dropdown-menu dropdown-menu-right shadow animated--fade-in" aria-labelledby="dropdownMenuLink">
                <div class="dropdown-header">Acciones:</div>
                <a class="dropdown-item" href="{% url 'inv:marca_new' %}"><i class="far fa-calendar-plus"></i>
                    Nueva</a>
            </div>
        </div>
    </div>
    <!-- Card Body -->
    <div class="card-body">
        {% if not obj %}
        <div class="alert alert-info">No hay marcas</div>
        {% else %}
        <table class="table table-striped table-hover">
            <thead>
                <th>Id</th>
                <th>Descripcion</th>
                <th>Estado</th>
                <th>Fecha Creado</th>
                <th>Fecha Modificado</th>
                <th class="all">Acciones</th>
            </thead>
            <tbody>
                {% for item in obj %}
                <tr>
                    <td>{{ item.id }}</td>
                    <td>{{ item.descripcion }}</td>
                    <td>{{ item.estado|yesno:"Activo,Inactivo" }}</td>
                    <td>{{ item.fecha_crea|date:"d/m/Y H:i:s" }}</td>
                    <td>{{ item.fecha_modif|date:"d/m/Y H:i:s" }}</td>
                    <td>
                        <a href="{% url 'inv:marca_edit' item.id %}" class="btn btn-warning btn-circle"
                            role="button"><i class="far fa-edit"></i></a>
                        <a href="{% url 'inv:marca_inactivate' item.id %}" class="btn btn-danger btn-circle"
                            role="button"><i class="far fa-trash-alt"></i></a>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        {% endif %}
    </div>
</div>

{% endblock page_content %}

{% block js_page %}
<script>
    //call the datatables jquery plugin
    $(document).ready(function () {
        $('.table').DataTable({
            "language": {
                "sProcessing": "Procesando...",
                "sLengthMenu": "Mostrar _MENU_ registros",
                "sZeroRecords": "No se encontraron resultados",
                "sEmptyTable": "Ningún dato disponible en esta tabla",
                "sInfo": "Mostrando registros del _START_ al _END_ de un total de _TOTAL_ registros",
                "sInfoEmpty": "Mostrando registros del 0 al 0 de un total de 0 registros",
                "sInfoFiltered": "(filtrado de un total de _MAX_ registros)",
                "sInfoPostFix": "",
                "sSearch": "Buscar:",
                "sUrl": "",
                "sInfoThousands": ",",
                "sLoadingRecords": "Cargando...",
                "oPaginate": {
                    "sFirst": "<span class='fa fa-angle-double-left'></span>",
                    "sLast": "<span class='fa fa-angle-double-right'></span>",
                    "sNext": "<span class='fa fa-angle-right'></span>",
                    "sPrevious": "<span class='fa fa-angle-left'></span>"
                },
                "oAria": {
                    "sSortAscending": ": Activar para ordenar la columna de manera ascendente",
                    "sSortDescending": ": Activar para ordenar la columna de manera descendente"
                }
            }
        });
    });
</script>
{% endblock js_page %}

inv/templates/inv/producto_list.html
{% extends 'base/layout.html' %}
{% block title %}Categorias de inventario{% endblock %}

{% block page_content %}
<!-- Dropdown Card Example -->
<div class="card shadow mb-4">
    <!-- Card Header - Dropdown -->
    <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
        <h6 class="m-0 font-weight-bold text-primary">Listado de productos</h6>
        <div class="dropdown no-arrow">
            <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown"
                aria-haspopup="true" aria-expanded="false">
                <i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"></i>
            </a>
            <div class="dropdown-menu dropdown-menu-right shadow animated--fade-in" aria-labelledby="dropdownMenuLink">
                <div class="dropdown-header">Acciones:</div>
                <a class="dropdown-item" onclick="return abrir_modal('{% url 'inv:producto_new' %}')" href="#"><i
                        class="far fa-calendar-plus"></i>
                    Nuevo</a>
            </div>
        </div>
    </div>
    <!-- Card Body -->
    <div class="card-body">
        {% if not obj %}
        <div class="alert alert-info">No hay productos</div>
        {% else %}
        <table class="table table-striped table-hover">
            <thead>
                <th>Sub.Cat.</th>
                <th>Codigo</th>
                <th>C.Barras</th>
                <th>Descripcion</th>
                <th>Existencia</th>
                <th>Marca</th>
                <th>U.M.</th>
                <th>Estado</th>
                <th class="all">Acciones</th>
            </thead>
            <tbody>
                {% for item in obj %}
                <tr>
                    <td>{{ item.subcategoria }}</td>
                    <td>{{ item.codigo }}</td>
                    <td>{{ item.codigo_barras }}</td>
                    <td>{{ item.descripcion }}</td>
                    <td>{{ item.existencia }}</td>
                    <td>{{ item.marca }}</td>
                    <td>{{ item.unidad_medida }}</td>
                    <td>{{item.estado|yesno:"Activo,Inactivo"}}</td>
                    <td>
                        <button class="btn btn-warning btn-circle" onclick="return abrir_modal('{% url 'inv:producto_edit' item.id %}')">
                            <i class="far fa-edit"></i></button>
                        <a href="{% url 'inv:producto_inactivate' item.id %}" class="btn btn-danger btn-circle"
                            role="button"><i class="far fa-trash-alt"></i></a>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        {% endif %}
    </div>
</div>

{% endblock page_content %}

{% block js_page %}
<script>
    //call the datatables jquery plugin
    $(document).ready(function () {
        $('.table').DataTable({
            "language": {
                "sProcessing": "Procesando...",
                "sLengthMenu": "Mostrar _MENU_ registros",
                "sZeroRecords": "No se encontraron resultados",
                "sEmptyTable": "Ningún dato disponible en esta tabla",
                "sInfo": "Mostrando registros del _START_ al _END_ de un total de _TOTAL_ registros",
                "sInfoEmpty": "Mostrando registros del 0 al 0 de un total de 0 registros",
                "sInfoFiltered": "(filtrado de un total de _MAX_ registros)",
                "sInfoPostFix": "",
                "sSearch": "Buscar:",
                "sUrl": "",
                "sInfoThousands": ",",
                "sLoadingRecords": "Cargando...",
                "oPaginate": {
                    "sFirst": "<span class='fa fa-angle-double-left'></span>",
                    "sLast": "<span class='fa fa-angle-double-right'></span>",
                    "sNext": "<span class='fa fa-angle-right'></span>",
                    "sPrevious": "<span class='fa fa-angle-left'></span>"
                },
                "oAria": {
                    "sSortAscending": ": Activar para ordenar la columna de manera ascendente",
                    "sSortDescending": ": Activar para ordenar la columna de manera descendente"
                }
            }
        });
    });
</script>
{% endblock js_page %}