app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include(('bases.urls','bases'), namespace='bases')),
    path('inv/', include(('inv.urls','inv'), namespace='inv')),
    path('cmp/', include(('cmp.urls','cmp'), namespace='cmp')),
    path('fac/', include(('fac.urls','fac'), namespace='fac')),
    path('admin/', admin.site.urls),
]

cmp/urls.py
from django.urls import path
from .views import ProveedorView, ProveedorNew, ProveedorEdit, ProveedorInactivate, ComprasView, Compras, ComprasDetalleDelete
from .reportes import reporte_compras, reporte_compra

urlpatterns = [
    path('proveedores/',ProveedorView.as_view(), name='proveedor_list'),
    path('proveedores/new',ProveedorNew.as_view(), name='proveedor_new'),
    path('proveedores/edit/<int:pk>',ProveedorEdit.as_view(), name='proveedor_edit'),
    path('proveedores/delete/<int:id>',ProveedorInactivate, name='proveedor_inactivate'),

    path('compras/',ComprasView.as_view(), name='compras_list'),
    path('compras/new',Compras, name='compras_new'),
    path('compras/edit/<int:compra_id>',Compras, name='compras_edit'),
    path('compras/<int:compra_id>/delete/<int:pk>',ComprasDetalleDelete.as_view(), name='compras_del'),

    path('compras/listado',reporte_compras, name='compras_print_all'),
    path('compras/<int:compra_id>/imprimir',reporte_compra, name='compras_print_one'),
]

inv/urls.py
from django.urls import path
from .views import CategoriaView, CategoriaNew, CategoriaEdit, CategoriaDel, SubCategoriaView, SubCategoriaNew, SubCategoriaEdit, SubCategoriaDel, MarcaView, MarcaNew, MarcaEdit, MarcaInactivate, UnidadMedidaView, UnidadMedidaNew, UnidadMedidaEdit, UnidadMedidaInactivate, ProductoView, ProductoNew, ProductoEdit, ProductoInactivate

urlpatterns = [
    path('categorias/',CategoriaView.as_view(), name='categoria_list'),
    path('categorias/new',CategoriaNew.as_view(), name='categoria_new'),
    path('categorias/edit/<int:pk>',CategoriaEdit.as_view(), name='categoria_edit'),
    path('categorias/delete/<int:pk>',CategoriaDel.as_view(), name='categoria_del'),

    path('subcategorias/',SubCategoriaView.as_view(), name='subcategoria_list'),
    path('subcategorias/new',SubCategoriaNew.as_view(), name='subcategoria_new'),
    path('subcategorias/edit/<int:pk>',SubCategoriaEdit.as_view(), name='subcategoria_edit'),
    path('subcategorias/delete/<int:pk>',SubCategoriaDel.as_view(), name='subcategoria_del'),

    path('marcas/',MarcaView.as_view(), name='marca_list'),
    path('marcas/new',MarcaNew.as_view(), name='marca_new'),
    path('marcas/edit/<int:pk>',MarcaEdit.as_view(), name='marca_edit'),
    path('marcas/inactivate/<int:id>',MarcaInactivate, name='marca_inactivate'),

    path('unidades-medida/',UnidadMedidaView.as_view(), name='unidadmedida_list'),
    path('unidades-medida/new',UnidadMedidaNew.as_view(), name='unidadmedida_new'),
    path('unidades-medida/edit/<int:pk>',UnidadMedidaEdit.as_view(), name='unidadmedida_edit'),
    path('unidades-medida/inactivate/<int:id>',UnidadMedidaInactivate, name='unidadmedida_inactivate'),

    path('productos/',ProductoView.as_view(), name='producto_list'),
    path('productos/new',ProductoNew.as_view(), name='producto_new'),
    path('productos/edit/<int:pk>',ProductoEdit.as_view(), name='producto_edit'),
    path('productos/inactivate/<int:id>',ProductoInactivate, name='producto_inactivate'),
]

cmp/models.py
from django.db import models
from bases.models import ClaseModelo
from inv.models import Producto
from django.db.models import Sum

#importar signals
from django.db.models.signals import post_save, post_delete
from django.dispatch import receiver

class Proveedor(ClaseModelo):
    descripcion = models.CharField(
        max_length=100,
        unique=True
    )
    direccion = models.CharField(
        max_length=250,
        null=True, 
        blank=True
    )
    contacto = models.CharField(
        max_length=100
    )
    telefono = models.CharField(
        max_length=10,
        null=True,
        blank=True
    )
    email = models.CharField(
        max_length=250,
        null=True,
        blank=True
    )

    def __str__(self):
        return '{}'.format(self.descripcion)

    def save(self):
        self.descripcion = self.descripcion.upper()
        super(Proveedor, self).save()

    class Meta:
        verbose_name_plural = 'Proveedores'


class ComprasEncabezado(ClaseModelo):
    fecha_compra = models.DateField(null=True, blank=True)
    observaciones = models.TextField(blank=True, null=True)
    no_factura = models.CharField(max_length=100)
    fecha_factura = models.DateField()
    sub_total = models.FloatField(default=0)
    descuento = models.FloatField(default=0)
    total = models.FloatField(default=0)

    proveedor = models.ForeignKey(Proveedor,on_delete=models.CASCADE)

    def __str__(self):
        return '{}'.format(self.observaciones)

    def save(self):
        self.observaciones = self.observaciones.upper()
        self.total = self.sub_total - self.descuento
        super(ComprasEncabezado, self).save()

    class Meta:
        verbose_name_plural = 'Encabezado Compras'
        verbose_name = 'Encabezado Compra'


class ComprasDetalle(ClaseModelo):
    cantidad = models.BigIntegerField(default=0)
    precio_proveedor = models.FloatField(default=0)
    sub_total = models.FloatField(default=0)
    descuento = models.FloatField(default=0)
    total = models.FloatField(default=0)
    costo = models.FloatField(default=0)

    compra = models.ForeignKey(ComprasEncabezado, on_delete=models.CASCADE)
    producto = models.ForeignKey(Producto, on_delete=models.CASCADE)

    def __str__(self):
        return '{}'.format(self.producto)

    def save(self):
        self.sub_total = float(float(int(self.cantidad)) * float(self.precio_proveedor))
        self.total = self.sub_total - float(self.descuento)
        super(ComprasDetalle, self).save()

    class Meta:
        verbose_name_plural = 'Detalle Compras'
        verbose_name = 'Detalle Compra'


@receiver(post_delete, sender=ComprasDetalle)
def detalle_compra_delete(sender, instance, **kwargs):
    #instancia es el objeto que se esta eliminando
    id_producto = instance.producto.id
    id_compra = instance.compra.id

    enca = ComprasEncabezado.objects.filter(pk=id_compra).first()
    if enca:
        sub_total = ComprasDetalle.objects.filter(compra=id_compra).aggregate(Sum('sub_total'))
        descuento = ComprasDetalle.objects.filter(compra=id_compra).aggregate(Sum('descuento'))
        enca.sub_total = sub_total['sub_total__sum']
        enca.descuento = descuento['descuento__sum']
        enca.save()

    producto = Producto.objects.filter(pk=id_producto).first()
    if producto:
        cantidad = int(producto.existencia)-int(instance.cantidad)
        producto.existencia = cantidad
        producto.save()


@receiver(post_save, sender=ComprasDetalle)
def detalle_compra_save(sender, instance, **kwargs):
    id_producto = instance.producto.id
    fecha_compra = instance.compra.fecha_compra

    producto = Producto.objects.filter(pk=id_producto).first()
    if producto:
        cantidad = int(producto.existencia)+int(instance.cantidad)
        producto.existencia = cantidad
        producto.ultima_compra = fecha_compra
        producto.save()

cmp/forms.py
from django import forms
from django.db import models
from django.forms import fields, widgets
from .models import Proveedor, ComprasEncabezado

class ProveedorForm(forms.ModelForm):
    email = forms.EmailField(max_length=250)
    class Meta:
        model = Proveedor
        exclude = ['user_modifi','fecha_modif','user_crea','fecha_crea']
        widget = {'descripcion':forms.TextInput}

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({
                'class':'form-control'
            })


class ComprasEncabezadoForm(forms.ModelForm):
    fecha_comra = forms.DateInput()
    fecha_factura = forms.DateInput()

    class Meta:
        model = ComprasEncabezado
        fields = ['proveedor','fecha_compra','observaciones','no_factura','fecha_factura','sub_total','descuento','total']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({
                'class':'form-control'
            })
        self.fields['fecha_compra'].widget.attrs['readonly'] = True
        self.fields['fecha_factura'].widget.attrs['readonly'] = True
        self.fields['sub_total'].widget.attrs['readonly'] = True
        self.fields['descuento'].widget.attrs['readonly'] = True
        self.fields['total'].widget.attrs['readonly'] = True

cmp/views.py
from typing import Coroutine, KeysView
from django.shortcuts import redirect, render
from django.views import generic
from django.urls import reverse_lazy
import datetime

from django.http import HttpResponse
import json
from django.db.models import Sum

from .models import Proveedor, ComprasEncabezado, ComprasDetalle
from inv.models import Producto
from .forms import ProveedorForm, ComprasEncabezadoForm

#mensajes para funciones
from django.contrib import messages
#mensajes para clases
from django.contrib.messages.views import SuccessMessageMixin
#para pasarle la funcion sin privilegios a clases
from bases.views import SinPrivilegios
#para pasarle la funcion login y permission a las funciones
from django.contrib.auth.decorators import login_required, permission_required

class ProveedorView(SinPrivilegios, generic.ListView):
    permission_required = 'cmp.view_proveedor'
    model = Proveedor
    template_name = 'cmp/proveedor_list.html'
    context_object_name = 'obj'


class ProveedorNew(SuccessMessageMixin, SinPrivilegios, generic.CreateView):
    permission_required = 'cmp.add_proveedor'
    model = Proveedor
    template_name = 'cmp/proveedor_form.html'
    context_object_name = 'obj'
    form_class = ProveedorForm
    success_message = 'Proveedor creado'
    success_url = reverse_lazy('cmp:proveedor_list')

    def form_valid(self, form):
        form.instance.user_crea = self.request.user
        return super().form_valid(form)


class ProveedorEdit(SuccessMessageMixin, SinPrivilegios, generic.UpdateView):
    permission_required = 'cmp.change_proveedor'
    model = Proveedor
    template_name = 'cmp/proveedor_form.html'
    context_object_name = 'obj'
    form_class = ProveedorForm
    success_message = 'Proveedor actualizado'
    success_url = reverse_lazy('cmp:proveedor_list')

    def form_valid(self, form):
        form.instance.user_modifi = self.request.user.id
        return super().form_valid(form)

@login_required(login_url='/login/')
@permission_required('cmp.change_proveedor',login_url='bases:sin_privilegios')
def ProveedorInactivate(request, id):
    template_name = 'cmp/cmp_del.html'
    contexto = {}
    proveedor = Proveedor.objects.filter(pk=id).first()

    if not proveedor:
        return HttpResponse('el proveedor no existe ' + str(id))

    if request.method == 'GET':
        contexto = {'obj': proveedor}

    if request.method == 'POST':
        proveedor.estado = False
        proveedor.save()
        messages.success(request, 'Proveedor inactivado')
        contexto = {'obj': 'OK'}
        return HttpResponse('proveedor inactivado')

    return render(request, template_name, contexto)


class ComprasView(SinPrivilegios, generic.ListView):
    permission_required = 'cmp.view_comprasencabezado'
    model = ComprasEncabezado
    template_name = 'cmp/compras_list.html'
    context_object_name = 'obj'


@login_required(login_url='/login/')
@permission_required('cmp.view_comprasencabezado',login_url='bases:sin_privilegios')
def Compras(request,compra_id=None):
    template_name = 'cmp/compras.html'
    productos = Producto.objects.filter(estado=True)
    form_compras = {}
    contexto = {}

    if request.method == 'GET':
        form_compras = ComprasEncabezadoForm()
        encabezado = ComprasEncabezado.objects.filter(pk = compra_id).first()

        #se envia el formulario con los valores inicializados si existieran
        if encabezado:
            detalle = ComprasDetalle.objects.filter(compra = encabezado)
            fecha_compra = datetime.date.isoformat(encabezado.fecha_compra)
            fecha_factura = datetime.date.isoformat(encabezado.fecha_factura)
            data = {
                'fecha_compra': fecha_compra,
                'proveedor': encabezado.proveedor,
                'fecha_factura': fecha_factura,
                'observaciones': encabezado.observaciones,
                'no_factura': encabezado.no_factura,
                'sub_total': encabezado.sub_total,
                'descuento': encabezado.descuento,
                'total': encabezado.total
            }
            form_compras = ComprasEncabezadoForm(data)
        else:
            detalle = None

        contexto = {'productos':productos, 'encabezado':encabezado, 'detalle':detalle, 'form_encabezado':form_compras}

    if request.method == 'POST':
        fecha_compra = request.POST.get('fecha_compra')
        observaciones = request.POST.get('observaciones')
        no_factura = request.POST.get('no_factura')
        fecha_factura = request.POST.get('fecha_factura')
        proveedor = request.POST.get('proveedor')
        sub_total = 0
        descuento = 0
        total = 0

        if not compra_id:
            prov = Proveedor.objects.get(pk=proveedor)
            enca = ComprasEncabezado(
                fecha_compra = request.POST.get('fecha_compra'),
                observaciones = request.POST.get('observaciones'),
                no_factura = request.POST.get('no_factura'),
                fecha_factura = request.POST.get('fecha_factura'),
                proveedor = prov,
                user_crea = request.user
            )
            
            if enca:
                enca.save()
                compra_id = enca.id
        else:
            enca = ComprasEncabezado.objects.filter(pk=compra_id).first()
            if enca:
                enca.fecha_compra = fecha_compra
                enca.observaciones = observaciones
                enca.no_factura = no_factura
                enca.fecha_factura = fecha_factura
                enca.user_modifi = request.user.id
                enca.save()

        if not compra_id:
            return redirect('cmp:compras_list')

        producto = request.POST.get('id_id_producto')
        cantidad = request.POST.get('id_cantidad_detalle')
        precio = request.POST.get('id_precio_detalle')
        sub_total_detalle = request.POST.get('id_sub_total_detalle')
        descuento_detalle = request.POST.get('id_descuento_detalle')
        total_detalle = request.POST.get('id_total_detalle')

        prod = Producto.objects.get(pk=producto)

        det = ComprasDetalle(
            compra = enca,
            producto = prod,
            cantidad = cantidad,
            precio_proveedor = precio,
            descuento = descuento_detalle,
            costo = 0,
            user_crea =  request.user
        )

        if det:
            det.save()
            
            sub_total = ComprasDetalle.objects.filter(compra=compra_id).aggregate(Sum('sub_total'))
            descuento = ComprasDetalle.objects.filter(compra=compra_id).aggregate(Sum('descuento'))
            enca.sub_total = sub_total['sub_total__sum']
            enca.descuento = descuento['descuento__sum']
            enca.save()

        return redirect('cmp:compras_edit',compra_id=compra_id)

    return render(request, template_name, contexto)


class ComprasDetalleDelete(SinPrivilegios, generic.DeleteView):
    permission_required = 'cmp.delete_comprasdetalle'
    model = ComprasDetalle
    template_name = 'cmp/compras_det_del.html'
    context_object_name = 'obj'

    def get_success_url(self):
        compra_id = self.kwargs['compra_id']
        return reverse_lazy('cmp:compras_edit', kwargs = {'compra_id':compra_id}) 

cmp/templates/cmp/cmp_del.html
<div class="modal-dialog modal-sm">
    <div class="modal-content">

        {% if obj %}
        <form method="POST" role="form" class="form-inline" action="{% url 'cmp:proveedor_edit' obj.pk %}">
            {% else %}
            <form method="POST" role="form" class="form-inline" action="{% url 'cmp:proveedor_new' %}">
                {% endif %}
                {% csrf_token %}
                <div class="col">
                    <div class="card border-left-danger shadow h-100 py-2">
                        <div class="card-body">
                            <div class="row no-gutters align-items-center">
                                <div class="col mr-2">
                                    <div class="text-xs font-weight-bold text-warning text-uppercase">
                                        <div class="alert">
                                            ¿ Inactivar {{ obj.descripcion }}?
                                        </div>
                                    </div>
                                    <div class="row">
                                        <button type="button" id="btnInactivar" class="btn btn-danger"><i
                                                class="far fa-question-circle"></i>Inactivar</button>
                                        <button type="button" onclick="return cerrar_modal()" class="btn btn-success">
                                            Cancelar
                                        </button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </form>

    </div>
</div>

<script>
    $(document).ready(function (){

        var token = $('input[name=csrfmiddlewaretoken]').val()
        $.ajaxSetup({
            beforeSend: function(xhr, settings){
                if(!(/^http:.*/.test(settings.url) || /^https:.*/.test(settings.url))){
                    xhr.setRequestHeader('X-CSRFToken',token);
                }
            }
        });

        $('#btnInactivar').click(function(e){
            e.preventDefault();
            id = {{ obj.id }};
            var template = '{% url 'cmp:proveedor_inactivate' obj.id %}';
            var data = {'id':id};
            data = JSON.stringify(data);

            $.ajax({
                type: "POST",
                url: template,
                data: data,
                beforeSend: function(xhr, settings){
                    $.ajaxSettings.beforeSend(xhr, settings);
                },
                success: function(response){
                    cerrar_modal();
                    var tipo = (response.startsWith('el proveedor no existe ') ? 'red':'green');
                    mensaje(response, tipo);
                },
                error: function(jqXHR, textStatus, errorThrow){
                    mensaje(errorThrow,'red');
                    cerrar_modal();
                }
            });
        });
    });
</script>

cmp/templates/cmp/compras_list.html
{% extends 'base/layout.html' %}
{% block title %}Categorias de compras{% endblock %}

{% block page_content %}
<!-- Dropdown Card Example -->
<div class="card shadow mb-4">
    <!-- Card Header - Dropdown -->
    <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
        <h6 class="m-0 font-weight-bold text-primary">Listado de compras</h6>
        <div class="dropdown no-arrow">
            <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown"
                aria-haspopup="true" aria-expanded="false">
                <i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"></i>
            </a>
            <div class="dropdown-menu dropdown-menu-right shadow animated--fade-in" aria-labelledby="dropdownMenuLink">
                <div class="dropdown-header">Acciones:</div>
                <a class="dropdown-item" href="{% url 'cmp:compras_new' %}"><i class="far fa-calendar-plus"></i>
                    Nueva</a>
                <a class="dropdown-item" href="{% url 'cmp:compras_print_all' %}" target="_blank"><i class="fas fa-print"></i>
                    Listado de compras</a>
            </div>
        </div>
    </div>
    <!-- Card Body -->
    <div class="card-body">
        {% if not obj %}
        <div class="alert alert-info">No hay compras</div>
        {% else %}
        <table class="table table-striped table-hover">
            <thead>
                <th>Id</th>
                <th>Fecha</th>
                <th>Observación</th>
                <th>No. Factura</th>
                <th>F. Factura</th>
                <th>Sub Total</th>
                <th>Descuento</th>
                <th>Total</th>
                <th>Estado</th>
                <th class="all">Acciones</th>
            </thead>
            <tbody>
                {% for item in obj %}
                <tr>
                    <td>{{ item.id }}</td>
                    <td>{{ item.fecha_compra }}</td>
                    <td>{{item.observaciones}}</td>
                    <td>{{ item.no_factura }}</td>
                    <td>{{ item.fecha_factura|date:"d/m/Y" }}</td>
                    <td>{{ item.sub_total }}</td>
                    <td>{{ item.descuento }}</td>
                    <td>{{ item.total }}</td>
                    <td>{{item.estado|yesno:"Activo,Inactivo"}}</td>
                    <td>
                        <a class="btn btn-warning btn-circle" href="{% url 'cmp:compras_edit' item.id %}"><i
                                class="far fa-edit"></i></a>
                        <a class="btn btn-success btn-circle" href="{% url 'cmp:compras_print_one' item.id %} "
                            target="_blank"><i class="fas fa-print"></i></a>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        {% endif %}
    </div>
</div>

{% endblock page_content %}

{% block js_page %}
<script>
    //call the datatables jquery plugin
    $(document).ready(function () {
        $('.table').DataTable({
            "language": {
                "sProcessing": "Procesando...",
                "sLengthMenu": "Mostrar _MENU_ registros",
                "sZeroRecords": "No se encontraron resultados",
                "sEmptyTable": "Ningún dato disponible en esta tabla",
                "sInfo": "Mostrando registros del _START_ al _END_ de un total de _TOTAL_ registros",
                "sInfoEmpty": "Mostrando registros del 0 al 0 de un total de 0 registros",
                "sInfoFiltered": "(filtrado de un total de _MAX_ registros)",
                "sInfoPostFix": "",
                "sSearch": "Buscar:",
                "sUrl": "",
                "sInfoThousands": ",",
                "sLoadingRecords": "Cargando...",
                "oPaginate": {
                    "sFirst": "<span class='fa fa-angle-double-left'></span>",
                    "sLast": "<span class='fa fa-angle-double-right'></span>",
                    "sNext": "<span class='fa fa-angle-right'></span>",
                    "sPrevious": "<span class='fa fa-angle-left'></span>"
                },
                "oAria": {
                    "sSortAscending": ": Activar para ordenar la columna de manera ascendente",
                    "sSortDescending": ": Activar para ordenar la columna de manera descendente"
                }
            }
        });
    });
</script>
{% endblock js_page %}

cmp/templates/cmp/proveedor_form.html
<div class="modal-dialog modal-lg">
    <div class="modal-content">

        {% if obj %}
        <form method="POST" role="form" class="form-inline" action="{% url 'cmp:proveedor_edit' obj.pk %}">
            {% else %}
            <form method="POST" role="form" class="form-inline" action="{% url 'cmp:proveedor_new' %}">
                {% endif %}
                {% csrf_token %}
                <div class="col-xl-12 col-md-12 mb-12">
                    {% if obj %}
                    <div class="card border-left-warning shadow h-100 py-2">
                        {% else %}
                        <div class="card border-left-success shadow h-100 py-2">
                            {% endif %}
                            <div class="card-body">
                                <div class="row no-gutters align-items-center">
                                    <div class="col mr-2">
                                        <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">
                                            {% if obj %} Editar {% else %} Nuevo {% endif %} proveedor
                                        </div>
                                        <div class="dropdown-divider"></div>
                                        <div class="row">
                                            {{ form.as_p }}
                                        </div>
                                        <div class="dropdown-divider"></div>
                                        <div class="row">
                                            <div class="col-10">
                                                <button type="submit" class="btn btn-success"><span
                                                        class="fa fa-save"></span>Guardar</button>
                                                <!-- <a href="{% url 'inv:producto_list' %}" class="btn btn-danger"><span
                                                        class="fa fa-undo"></span>Cancelar</a> -->
                                                <button type="button" onclick="return cerrar_modal()" class="btn btn-danger">
                                                    Cancelar
                                                </button>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
            </form>

    </div>
</div>

cmp/templates/cmp/proveedor_list.html
{% extends 'base/layout.html' %}
{% block title %}Categorias de compras{% endblock %}

{% block page_content %}
<!-- Dropdown Card Example -->
<div class="card shadow mb-4">
    <!-- Card Header - Dropdown -->
    <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
        <h6 class="m-0 font-weight-bold text-primary">Listado de proveedores</h6>
        <div class="dropdown no-arrow">
            <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown"
                aria-haspopup="true" aria-expanded="false">
                <i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"></i>
            </a>
            <div class="dropdown-menu dropdown-menu-right shadow animated--fade-in" aria-labelledby="dropdownMenuLink">
                <div class="dropdown-header">Acciones:</div>
                <a class="dropdown-item" onclick="return abrir_modal('{% url 'cmp:proveedor_new' %}')" href="#"><i
                        class="far fa-calendar-plus"></i>
                    Nuevo</a>
            </div>
        </div>
    </div>
    <!-- Card Body -->
    <div class="card-body">
        {% if not obj %}
        <div class="alert alert-info">No hay proveedores</div>
        {% else %}
        <table class="table table-striped table-hover">
            <thead>
                <th>Id</th>
                <th>Descripcion</th>
                <th>Dirección</th>
                <th>Contacto</th>
                <th>Teléfono</th>
                <th>EMail</th>
                <th>Estado</th>
                <th class="all">Acciones</th>
            </thead>
            <tbody>
                {% for item in obj %}
                <tr>
                    <td>{{ item.id }}</td>
                    <td>{{ item.descripcion }}</td>
                    <td>{{item.direccion}}</td>
                    <td>{{ item.contacto }}</td>
                    <td>{{ item.telefono }}</td>
                    <td>{{ item.email }}</td>
                    <td>{{item.estado|yesno:"Activo,Inactivo"}}</td>
                    <td>
                        <button class="btn btn-warning btn-circle"
                            onclick="return abrir_modal('{% url 'cmp:proveedor_edit' item.id %}')">
                            <i class="far fa-edit"></i></button>
                        <button class="btn btn-danger btn-circle"
                            onclick="return abrir_modal('{% url 'cmp:proveedor_inactivate' item.id %}')">
                            <i class="far fa-thumbs-down"></i></button>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        {% endif %}
    </div>
</div>

{% endblock page_content %}

{% block js_page %}
<script>
    //call the datatables jquery plugin
    $(document).ready(function () {
        $('.table').DataTable({
            "language": {
                "sProcessing": "Procesando...",
                "sLengthMenu": "Mostrar _MENU_ registros",
                "sZeroRecords": "No se encontraron resultados",
                "sEmptyTable": "Ningún dato disponible en esta tabla",
                "sInfo": "Mostrando registros del _START_ al _END_ de un total de _TOTAL_ registros",
                "sInfoEmpty": "Mostrando registros del 0 al 0 de un total de 0 registros",
                "sInfoFiltered": "(filtrado de un total de _MAX_ registros)",
                "sInfoPostFix": "",
                "sSearch": "Buscar:",
                "sUrl": "",
                "sInfoThousands": ",",
                "sLoadingRecords": "Cargando...",
                "oPaginate": {
                    "sFirst": "<span class='fa fa-angle-double-left'></span>",
                    "sLast": "<span class='fa fa-angle-double-right'></span>",
                    "sNext": "<span class='fa fa-angle-right'></span>",
                    "sPrevious": "<span class='fa fa-angle-left'></span>"
                },
                "oAria": {
                    "sSortAscending": ": Activar para ordenar la columna de manera ascendente",
                    "sSortDescending": ": Activar para ordenar la columna de manera descendente"
                }
            }
        });
    });
</script>
{% endblock js_page %}